services:
  - type: web
    name: swasthya-sakhi
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py seed_demo_users && python manage.py collectstatic --noinput
    startCommand: gunicorn arogyamitra.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: swasthya-sakhi-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: swasthya-sakhi-db
    plan: free
    databaseName: swasthya_sakhi
